version: "3"
services:

 prometheus:
  image: prom/prometheus
  container_name: prometheus
  hostname: prometheus
  volumes:
   - $PWD/cfg/prometheus.yml:/etc/prometheus/prometheus.yml
  command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
  ports:
   - 9090:9090

 influx:
  image: influxdb:alpine
  container_name: influxdb
  restart: always
  ports:
    - 8086:8086
  volumes:
    - $PWD/cfg/influxdb:/var/lib/influxdb
  environment:
    - INFLUXDB_DB=salt
    - INFLUXDB_USER=salt
    - INFLUXDB_USER_PASSWORD=password
    - INFLUXDB_ADMIN_ENABLED=true
    - INFLUXDB_ADMIN_USER=admin 
    - INFLUXDB_ADMIN_PASSWORD=password 
    - DOCKER_INFLUXDB_INIT_ORG=my-org
    - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket

 grafana:
  image: grafana/grafana
  container_name: grafana
  volumes:
    - $PWD/cfg/grafana/:/etc/grafana/provisioning/
  ports:
   - 3030:3000
  environment:
   - GF_AUTH_ANONYMOUS_ENABLED=true

 postgres:
  image: postgres
  restart: always
  container_name: postgres
  ports:
   - 5432:5432
  environment:
   - POSTGRES_USER=salt
   - POSTGRES_DB=api
   - POSTGRES_PASSWORD=salt
  volumes:
   - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql

 app:
  image: saltaaron/crud-app
  container_name: crud-app
  hostname: crud-app
  depends_on:
   - postgres
  ports:
   - 3000:3000

 kong-postgres:
  image: postgres
  restart: always
  container_name: kong-postgres
  ports:
   - 5433:5432
  environment:
   - POSTGRES_USER=kong
   - POSTGRES_DB=kong
   - POSTGRES_PASSWORD=kong
 kong-ent-bootstrap:
  image: saltaaron/salted-kong
  container_name: kong-ent-bootstrap
  hostname: kongBootstrap
  depends_on:
   - kong-postgres
  restart: on-failure
  command: "kong migrations bootstrap"
  environment:
   - KONG_PASSWORD=KingKong
   - KONG_AUDIT_LOG=on
   - KONG_LOG_LEVEL=debug
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=kong-postgres
   - KONG_PG_PASSWORD=kong

 kong-ent1:
  image: saltaaron/salted-kong
  container_name: kong-ent1
  hostname: kongNode1
  depends_on:
   - kong-postgres
   - kong-ent-bootstrap
  restart: always
  ports:
   - 8000:8000
   - 8001:8001
   - 8443:8443
   - 8444:8444
   - 9080:9080
   - 9081:9081
  environment:
   - KONG_PLUGINS=bundled,salt-sensor
   - KONG_AUDIT_LOG=on
   - KONG_LOG_LEVEL=debug
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=kong-postgres
   - KONG_PG_PASSWORD=kong
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
   - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
